[phases.install]
cmds = [
  "npm ci --no-audit --prefer-offline --cache /tmp/.npm"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "NODE_OPTIONS='--max-old-space-size=4096' DISABLE_ESLINT_PLUGIN=true GENERATE_SOURCEMAP=false npm run build"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"